steps:
- name: 'gcr.io/cloud-builders/gsutil'
  # args: ['rsync', '-d', '-x', '.git', '-j', '-n', '-r', '/workspace/', 'gs://www.synaptic.cl']
  args: ['-m', 'cp', '-r', '/workspace/*', 'gs://www.synaptic.cl']
